# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.age$'
      - id: end-of-file-fixer
        exclude: '\.age$'
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: "nix-flake-check"
        name: "nix flake checker"
        description: "Will run command nix flake check"
        entry: "nix flake check --no-warn-dirty"
        language: "system"
        pass_filenames: false
        types: [nix]
