{
 "title": "Media Downloads / Overview",
 "tags": [
  "arr",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Prowlarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prowlarr_system_status\n", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"prowlarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(prowlarr_system_health_issues)",
     "legendFormat": "Health Issues"
    },
    {
     "expr": "max(prowlarr_indexer_enabled_total)",
     "legendFormat": "Enabled Indexers"
    },
    {
     "expr": "max(prowlarr_indexer_total - prowlarr_indexer_enabled_total)",
     "legendFormat": "Disabled Indexers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total[$__range]))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total[$__range]))",
     "legendFormat": "Grabs"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total[$__range]))",
     "legendFormat": "Query Failures"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prowlarr_indexer_average_response_time_ms)",
     "legendFormat": "Response Time"
    },
    {
     "expr": "sum(increase(prowlarr_indexer_failed_queries_total[$__range])) / sum(prowlarr_indexer_queries_total)",
     "legendFormat": "Failed Queries"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(prowlarr_indexer_vip_expires_in_seconds)",
     "legendFormat": "Nearest VIP Expiration"
    }
   ]
  },
  {
   "title": "Indexer Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(prowlarr_indexer_average_response_time_ms) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Agent Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(prowlarr_user_agent_queries_total[$__rate_interval])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_queries_total[$__range])) by (indexer)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by Indexer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_indexer_grabs_total[$__range])) by (indexer)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_queries_total[$__range])) by (user_agent)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grabs by User Agent",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prowlarr_user_agent_grabs_total[$__range])) by (user_agent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VIP Expiration",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "prowlarr_indexer_vip_expires_in_seconds",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() * 1000) + (prowlarr_indexer_vip_expires_in_seconds * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "prowlarr_system_health_issues", "legendFormat": "__auto" }
   ]
  },
  { "title": "Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_system_status\n", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"radarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "radarr_movie_monitored_total", "legendFormat": "Monitored" },
    { "expr": "radarr_movie_wanted_total", "legendFormat": "Wanted" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_queue_total", "legendFormat": "Queued" },
    { "expr": "radarr_movie_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "radarr_history_total", "legendFormat": "History" },
    { "expr": "radarr_movie_filesize_total", "legendFormat": "Disk Used" },
    {
     "expr": "radarr_rootfolder_freespace_bytes",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "radarr_movie_quality_total", "legendFormat": "{{quality}}" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"radarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"radarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "radarr_movie_filesize_total", "legendFormat": "Used" }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "targets": [
    { "expr": "radarr_system_health_issues", "legendFormat": "__auto" }
   ]
  },
  { "title": "Sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_system_status\n", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"sonarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_queue_total", "legendFormat": "Queued" },
    { "expr": "sonarr_history_total", "legendFormat": "History" },
    {
     "expr": "sonarr_episode_downloaded_total",
     "legendFormat": "Downloaded"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_series_monitored_total)",
     "legendFormat": "Series Monitored"
    },
    { "expr": "max(sonarr_series_total)", "legendFormat": "Series Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_season_monitored_total)",
     "legendFormat": "Seasons Monitored"
    },
    { "expr": "max(sonarr_season_total)", "legendFormat": "Seasons Total" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarr_episode_missing_total)",
     "legendFormat": "Episodes Missing"
    },
    { "expr": "max(sonarr_episode_total)", "legendFormat": "Episodes Total" }
   ]
  },
  {
   "title": "Qualities",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sonarr_episode_quality_total", "legendFormat": "{{quality}}" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"sonarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sonarr_series_filesize_bytes", "legendFormat": "Used" }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 69 },
   "targets": [
    { "expr": "sonarr_system_health_issues", "legendFormat": "__auto" }
   ]
  },
  { "title": "Readarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "readarr_system_status\n", "legendFormat": "Status" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{container=\"readarr\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "readarr_author_downloaded_total",
     "legendFormat": "Authors Downloaded"
    },
    { "expr": "readarr_author_monitored_total", "legendFormat": "Authors Monitored" },
    { "expr": "readarr_author_total", "legendFormat": "Authors Wanted" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "readarr_queue_total", "legendFormat": "Queued" },
    { "expr": "readarr_book_downloaded_total", "legendFormat": "Downloaded" },
    { "expr": "readarr_history_total", "legendFormat": "History" },
    { "expr": "readarr_author_filesize_bytes", "legendFormat": "Disk Used" },
    {
     "expr": "readarr_rootfolder_freespace_bytes",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"readarr.*\"}[$__rate_interval]))",
     "legendFormat": "Network Transmit"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"readarr.*\"}[$__rate_interval])) * -1",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "readarr_author_filesize_bytes", "legendFormat": "Used" }
   ]
  },
  {
   "title": "System Health Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 83 },
   "targets": [
    { "expr": "readarr_system_health_issues", "legendFormat": "__auto" }
   ]
  }
 ]
}