{
 "title": "GlobalTalk",
 "tags": [
  "prometheus",
  "globaltalk-exporter",
  "networking"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "![](https://marchintosh.com/images/GT_Logo.jpg)\n"
   }
  },
  {
   "title": "Updating?",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(globaltalk_zones)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Links",
   "type": "text",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "options": {
    "content": "* [GlobalTalk @ MARCHintosh.com](https://marchintosh.com/globaltalk.html)\n* [GlobalTalk Signup Form](https://docs.google.com/forms/d/e/1FAIpQLSfUnCeUzrhwI_T3n9udhX9UVfhePqIft5Nmy1Bsl_uB2r1PRQ/viewform?usp=sharing)\n* [GlobalTalk Google Doc](https://docs.google.com/spreadsheets/d/1_fgMgcAveaxkT1AQYSA4CHf6Mz3sB6CjgTpJQPXG4fw)\n* [MARCHintosh Fedi Account](https://bitbang.social/@MARCHintosh)\n\n"
   }
  },
  { "title": "GlobalTalk Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "GlobalTalk Zones",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(globaltalk_zones{})", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unique Devices",
   "type": "stat",
   "description": "A count of unique Node IDs on the GlobalTalk network that are discoverable by NBP.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(globaltalk_unique_devices)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Objects Online",
   "type": "stat",
   "description": "Objects can represent services or identifiers on devices that are shared on the AppleTalk network.",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(globaltalk_zone_devices)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unique Object Types",
   "type": "stat",
   "description": "The number of unique object types on the network. Types can either represent services, tools, or identifiers for hardware and software.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(globaltalk_device_types)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Printers Online",
   "type": "stat",
   "description": "A count of Printer objects currently visible by NBP, this looks for any object type of \"*Writer*\".",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(globaltalk_device_types{type=~\".*Writer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AFP Servers Online",
   "type": "stat",
   "description": "A count of AFP objects discoverable on the network, identified by a type of \"AFPServer\".",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(globaltalk_device_types{type=\"AFPServer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JRouter Versions",
   "type": "timeseries",
   "description": "Versions of JRouter visible on the network. Identified from the object name where the type is \"AppleRouter\".",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by(version)(globaltalk_jrouter_versions)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Cisco Routers",
   "type": "stat",
   "description": "A count of objects advertising the type of \"ciscoRouter\"",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(globaltalk_device_types{type=\"ciscoRouter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Known Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(jrouter_aurp_peer_sender_connected{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Known Peers Connected",
   "type": "stat",
   "description": "Percentage of peers connected from 'Doofnet' to the peers listed on the GlobalTalk Google Doc",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jrouter_aurp_peer_sender_connected) / count(jrouter_aurp_peer_sender_connected)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware / OS",
   "type": "bargauge",
   "description": "A count of objects with a type including \"Mac\", \"Darwin\", \"Power\", or \"Windows\".\n\nThis is usually enough to identify the hardware of physical Macs, Quadra 800s are usually QEMU images.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "globaltalk_device_types{type=~\"(.*Mac.*|Darwin|Power.*|.*Windows.*)\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Object Types",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (type) (globaltalk_device_types)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}