{
 "title": "Infra / Overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "A&A",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_network_transmit_bytes_total{device=\"pppoe1\"}[5m]))",
     "legendFormat": "Upstream"
    },
    {
     "expr": "avg(rate(node_network_receive_bytes_total{device=\"pppoe1\"}[5m]))",
     "legendFormat": "Downstream"
    }
   ]
  },
  {
   "title": "NAS Pool Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "{{ pool }}" }
   ]
  },
  {
   "title": "NAS Disk Temps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(serial) (disk_temperature{exported_instance=\"nas-03\"})",
     "legendFormat": "{{ serial }}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(speedtest_ping_latency_milliseconds[60m]))",
     "legendFormat": "Ping"
    },
    {
     "expr": "avg(avg_over_time(speedtest_jitter_latency_milliseconds[60m]))",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "WiFi Performance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (essid) (unpoller_client_satisfaction_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hetzner Storage Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hcloud_storagebox_data_size / hcloud_storagebox_quota",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (\n  rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"(svc|hyp)-.*\"}[5m])\n))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Prometheus Retention",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((time() - (prometheus_tsdb_lowest_timestamp / 1000)) / 84600)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}