{
 "title": "TrueNAS / Disk Insight",
 "tags": [
  "prometheus",
  "graphite-exporter",
  "truenas",
  "storage"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(uptime,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(uptime{job=\"$job\"},instance)"
    }
   },
   {
    "name": "disk",
    "label": "disks",
    "query": {
     "query": "label_values(disk_io{instance=\"$instance\", job=\"$job\"},disk)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{instance=~\"$instance\"}",
     "legendFormat": "synced"
    }
   ]
  },
  { "title": "Disk Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Disk utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_utilization{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_utilization{instance=~\"$instance\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Disk I/O - $disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "disk_io{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Disk I/O time - $disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "abs(disk_iotime{instance=~\"$instance\", disk=~\"$disk\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Disk IOps - $disk",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 61 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "abs(disk_io_ops{instance=~\"$instance\", disk=~\"$disk\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Disk Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Disk await - $disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "abs(disk_await{instance=~\"$instance\", disk=~\"$disk\"})",
     "legendFormat": "{{op}}"
    }
   ]
  },
  {
   "title": "Disk backlog + busy - $disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "disk_io_backlog{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "backlog"
    },
    {
     "expr": "disk_busy{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "busy"
    }
   ]
  },
  {
   "title": "Disk active operations - $disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "disk_qops{instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Disk avg I/O size - $disk",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
   "repeat": "disk",
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "abs(disk_io_size{instance=~\"$instance\", disk=~\"$disk\"})",
     "legendFormat": "{{op}}"
    }
   ]
  }
 ]
}