{
 "title": "UniFi-Poller: Client Insights - Prometheus",
 "description": "UniFi Poller v2.0.1 Displays detailed information for clients in a UniFi network using Prometheus.",
 "tags": [
  "prometheus",
  "unifi-poller",
  "unifi",
  "networking"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unpoller_client_uptime_seconds,source)"
   },
   {
    "name": "Site",
    "query": "label_values(unpoller_client_uptime_seconds{source=~\"$Controller\"},site_name)"
   },
   {
    "name": "AP",
    "query": "label_values(unpoller_client_uptime_seconds{site_name=~\"$Site\"},ap_name)"
   },
   {
    "name": "Switch",
    "query": "label_values(unpoller_client_uptime_seconds{site_name=~\"$Site\"},sw_name)"
   },
   {
    "name": "Wireless",
    "query": "label_values(unpoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\", wired=\"false\"},name)"
   },
   {
    "name": "Wired",
    "query": "label_values(unpoller_client_uptime_seconds{site_name=~\"$Site\", sw_name=~\"$Switch\", wired=\"true\"},name)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" },
   { "name": "Identifier", "query": "name, name\\,mac" }
  ]
 },
 "panels": [
  {
   "title": "Wireless Devices",
   "type": "table-old",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_receive_bytes_total{wired!=\"true\", site_name=~\"$Site\", name=~\"$Wireless\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_transmit_bytes_total{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unpoller_client_uptime_seconds{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\"})"
    }
   ]
  },
  {
   "title": "Wired Devices",
   "type": "table-old",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_uptime_seconds{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_receive_bytes_total{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    },
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unpoller_client_transmit_bytes_total{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})"
    }
   ]
  },
  {
   "title": "Clients / Channel",
   "type": "piechart",
   "description": "Visualize wireless channel usage w/ wired client counts.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (hostname) (unpoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})",
     "legendFormat": "Wired"
    },
    {
     "expr": "count by (channel) (unpoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "Channel {{channel}}"
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "piechart",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (radio_proto) (unpoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "{{radio_proto}}"
    }
   ]
  },
  {
   "title": "Client MAC OUI Breakdown",
   "type": "piechart",
   "description": "This shows an OUI breakdown from Unifi's perspective. e = wired, w = wireless",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 25 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (oui) (unpoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": " w {{oui}}"
    },
    {
     "expr": "count by (oui) (+unpoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\"})",
     "legendFormat": "e  {{oui}}"
    }
   ]
  },
  {
   "title": "UAP Bandwidth / Wireless Devices",
   "type": "graph",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Wired Devices",
   "type": "graph",
   "description": "Wired TX / RX bytes per second (calculated in 30 second buckets). Rx is on the negative axis. Does not include amazon and camera devices. Unaffected by the AP setting.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth / Echos & FireTVs",
   "type": "graph",
   "description": "Amazon Devices TX / RX bytes per second. Rx is on the negative axis. My home network has a ton of Amazon devices, so I broke them out separately. If you don't have Amazon devices, or they have different names, you can edit the query to use a different name. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name=~\"^amazon.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name=~\"^amazon.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{name=~\"^amazon.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{name=~\"^amazon.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth: Cameras",
   "type": "graph",
   "description": "Cameras TX / RX bytes per second. Rx is on the negative axis. This graph shows any device with the word \"camera\" in its name and has nothing to do with UniFi Protect/video products. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{ap_name=~\"$AP\", name=~\".*camera.*|.*cam$\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{ap_name=~\"$AP\", name=~\".*camera.*|.*cam$\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_bytes_total{sw_name=~\"$Switch\", name=~\".*camera.*|.*cam$\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_receive_bytes_total{sw_name=~\"$Switch\", name=~\".*camera.*|.*cam$\", site_name=~\"$Site\"}[$__interval]))",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "dB", "label": "RSSI Quality" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_rssi_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "dBm", "label": "Signal Power" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_signal_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "UAP Client Stats / Noise",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "dB", "label": "Noise" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_noise_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "TX Rate",
   "type": "graph",
   "description": "Client reported transmit rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_transmit_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Wifi Tx Attempts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short", "label": "Attempts / Second" }
   ],
   "targets": [
    {
     "expr": "avg by ($Identifier) (rate(unpoller_client_wifi_attempts_transmit_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "RX Rate",
   "type": "graph",
   "description": "Client reported receive rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_receive_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Transmit Retries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short", "label": "Tx Retries / Second" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unpoller_client_transmit_retries_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Transmit Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "dBm", "label": "Transmit Power dBm" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_radio_transmit_power_dbm{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Anomalies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short", "label": "Anomalies" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_anomalies{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Satisfaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "percentunit", "label": "Client Satisfaction" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_satisfaction_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Roam Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "short", "label": "Roam Count" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_roam_count_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Connection Quality %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "percentunit", "label": "CCQ" }
   ],
   "targets": [
    {
     "expr": "sum by ($Identifier) (unpoller_client_ccq_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  }
 ]
}