{
 "title": "Home / Overview",
 "tags": [
  "homeassistant",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PM2.5 Level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_pm25_u0xb5g_per_mu0xb3)"
    }
   ]
  },
  {
   "title": "Average Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_temperature_celsius{})",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Average Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_humidity_percent{})"
    }
   ]
  },
  {
   "title": "Average Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_pressure_hpa{})"
    }
   ]
  },
  {
   "title": "PM2.5 Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "sum by (friendly_name) (homeassistant_sensor_pm25_u0xb5g_per_mu0xb3)",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  }
 ]
}