{
 "title": "Infra / Overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 } },
  {
   "title": "A&A",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_network_transmit_bytes_total{device=\"pppoe1\"}[5m]))",
     "legendFormat": "Upstream"
    },
    {
     "expr": "avg(rate(node_network_receive_bytes_total{device=\"pppoe1\"}[5m]))",
     "legendFormat": "Downstream"
    }
   ]
  },
  {
   "title": "NAS Pool Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zfs_pool{state=\"online\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "NAS Disk Temps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(serial) (disk_temperature{exported_instance=\"nas-03\"})",
     "legendFormat": "{{ serial }}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(speedtest_ping_latency_milliseconds[60m]))",
     "legendFormat": "Ping"
    },
    {
     "expr": "avg(avg_over_time(speedtest_jitter_latency_milliseconds[60m]))",
     "legendFormat": "Jitter"
    }
   ]
  },
  {
   "title": "WiFi Performance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (essid) (unpoller_client_satisfaction_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (increase(broker_publish_messages_sent[$__rate_interval]) + increase(broker_publish_messages_received[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hetzner Storage Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hcloud_storagebox_data_size / hcloud_storagebox_quota",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  { "title": "K8s Prod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "K8S Prod Cluster Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}))\n\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "K8S Prod Cluster Disk",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(node_filesystem_free_bytes{mountpoint=\"/\", instance=~\"10.101.10.*\"}) / sum(node_filesystem_size_bytes{mountpoint=\"/\", instance=~\"10.101.10.*\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Kube Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (kubelet_version) (kube_node_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Longhorn Faults",
   "type": "stat",
   "description": "Fault volumes are volumes that doesn't have any healthy replica.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_robustness{}==3) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Longhorn Node Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg by (node) (longhorn_node_storage_usage_bytes/longhorn_node_storage_capacity_bytes)) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "ESX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (vmware_host_cpu_usage / vmware_host_cpu_max * 100)",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (vmware_host_memory_usage / vmware_host_memory_max)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (ds_name) (100 - ((vmware_datastore_freespace_size / vmware_datastore_capacity_size) * 100))",
     "legendFormat": "{{ds_name}}"
    }
   ]
  },
  {
   "title": "Prometheus Retention",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((time() - (prometheus_tsdb_lowest_timestamp / 1000)) / 84600)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Storage Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes/prometheus_tsdb_retention_limit_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}