{
 "title": "JRouter / Overview",
 "tags": [
  "jrouter",
  "prometheus",
  "networking"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "NetworkID",
    "label": "Network ID",
    "query": {
     "query": "label_values(jrouter_atalk_bytes_in_total,src_net)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JRouter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jrouter_aurp_peer_sender_connected{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Known Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(jrouter_aurp_peer_sender_connected{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Known Peers Connected",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jrouter_aurp_peer_sender_connected) / count(jrouter_aurp_peer_sender_connected)",
     "legendFormat": "Connected Peers"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Connections",
   "type": "stat",
   "description": "Peers that have timed out (5 retries)",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(jrouter_aurp_peer_send_retries{} >= 5)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ATalk: Router <-> $NetworkID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(jrouter_atalk_bytes_in_total{src_net=~\"$NetworkID\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(jrouter_atalk_bytes_out_total{src_net=~\"$NetworkID\"}[5m])) * -1",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "AURP Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(jrouter_aurp_bytes_in_total{}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(jrouter_aurp_bytes_out_total{}[5m])) * -1",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "AARP Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(jrouter_aarp_bytes_in_total{}[5m])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(jrouter_aarp_bytes_out_total{}[5m]) * -1",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "GlobalTalk Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GlobalTalk Zones",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "globaltalk_zones{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Endpoints Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(globaltalk_zone_devices)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AFP Servers Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "globaltalk_device_types{type=\"AFPServer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printers Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(globaltalk_device_types{type=~\".*Writer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jRouter Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 17 },
   "targets": [
    { "expr": "globaltalk_jrouter_versions", "legendFormat": "{{version}}" }
   ]
  }
 ]
}