{
 "title": "Mosquitto / Overview",
 "tags": [
  "mqtt",
  "mosquito",
  "prometheus",
  "homeassistant"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "query_result(broker_uptime{})" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "broker_uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Subscription count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "broker_subscriptions_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Clients connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "broker_clients_connected{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Transfered data sum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "broker_bytes_received{instance=\"$instance\"} + broker_bytes_sent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Published messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(broker_publish_messages_sent{instance=\"$instance\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "increase(broker_publish_messages_received{instance=\"$instance\"}[5m]) * -1",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Transfered data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(broker_bytes_sent{instance=\"$instance\"}[5m])",
     "legendFormat": "Sent"
    },
    {
     "expr": "increase(broker_bytes_received{instance=\"$instance\"}[5m])*-1",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Retained Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "broker_retained_messages_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Stored Messages Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "broker_store_messages_bytes{instance=\"$instance\"}"
    }
   ]
  }
 ]
}